### ISSUE TITLE
java port?

### ISSUE THREAD

**Issue by artknight** [polygonplanet/lzbase62#1]
Hi,
great work! Do you know if there is a port of this to other languages ( java, c#, ColdFusion, etc... ) ?

Thanks,

**Comment by polygonplanet** [comment]
Hi,
This module is my original algorithm, so there are no ports for other languages.
Thanks!

**Comment by artknight** [comment]
Would you be interested in porting it over to java?

**Comment by polygonplanet** [comment]
Yes, it's interesting. but I don't know java

**Comment by artknight** [comment]
I really like the algorithm so having a server-side language use it is a big plus. What server-side language are you savvy in?

**Comment by polygonplanet** [comment]
I had been used PHP. If you can port from JavaScript, we welcome implementation in other languages.

**Comment by irov** [comment]
Hello,
maybe port to C?

**Comment by polygonplanet** [comment]
If you port to C, we welcome the implementation.
Sorry, I'm not good at C.
