### ISSUE TITLE
Possible packaging issue

### ISSUE THREAD

**Issue by jfstephe** [polygonplanet/lzbase62#3]
Hi,
AFAICT after v1.4.6 the build output (lzbase62.js etc) are referring to './config' etc but that file isn't in the root directory (it's in the 'src' directory). I suspect there's an issue with packaging it. The demo still works as it's on the old 1.4.6 version.

Happy to be wrong :-)

Thanks for the library!
John

**Comment by polygonplanet** [comment]
Hi, John
'./config' is a virtual reference by the browserify and does not actually refer to './config'.
This will work without problems :)
I updated the lzbase64 version of the demo to 1.4.8
Thank you!

**Comment by polygonplanet** [comment]
Sorry, I confirmed a bug when require as module, and fixed that bug for can't find module
Thanks!

**Comment by jfstephe** [comment]
np. Thanks for double-checking! :-)
