### ISSUE TITLE
Bit level LZSS ?

### ISSUE THREAD

**Issue by 1000i100** [polygonplanet/lzbase62#5]
Hi, i'm looking for an LZSS implementation in js working on bit level and not only on Bytes level.

is there a theorical issue about this or it's just not implemented ?

PS : base62 could be usefull, but be able to use LZSS on ArrayBuffer (or string if not on bit level) and to choose to convert it to baseN look more modular to me.

**Comment by polygonplanet** [comment]
@1000i100 Hi, this lib's bit level is not implemented. I think BaseN is good way, but I want to keep simple APIs for fast conversion.
Thanks for your idea!

**Comment by brandonros** [comment]
does this work with binary files or not? not base62-encoded
